fluentd:
  image: fluent/fluentd
  volumes:
    - ./fluentd:/fluentd/etc
  ports:
    - "24224:24224"

app:
  build: app
  restart: always

nginx:
  build: nginx
  links:
    - app
    - fluentd
  ports:
    - 8080:80
  log_driver: fluentd
  log_opt:
    fluentd-address: "localhost:24224"
    fluentd-tag: "docker.{{.FullID}}"
  restart: always
